table _Measures
	lineageTag: 1b62d0e4-71fb-4ff5-93ab-a89b1ea9bc0c

	measure SelectedQueryMessage =
			
			IF(SELECTEDVALUE('AM_Prompts'[Message]) = "Choose a question to ask...", BLANK(), SELECTEDVALUE('AM_Prompts'[Message]))
		lineageTag: 886137fc-eded-406b-a27d-ac0dd4368de2

	measure 'Prompt (Current User)' =
			
			VAR email = [User Email]
			RETURN
			LOOKUPVALUE(
			    'AM_Sessions'[Prompt],
			    'AM_Sessions'[Username], email
			)
		lineageTag: 62c82263-5f6d-4b9f-a2ea-8c3c3dd36f8c

	measure PromptMeasure = "Provide an executive summary, indicating important takeaways."
		lineageTag: e05f37ba-7291-47aa-a25f-5f7ae2314f73

	measure 'User Email' =
			
			USERPRINCIPALNAME()
		lineageTag: 75a98dd9-81c6-44bb-9347-dc0b286c3ddc

	measure FilterStringAS = ```
			
			
			-- UAID
			VAR AllUAIDsCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[UAID]), ALL('AM_AssetRegister'))
			VAR SelectedUAIDsCount = DISTINCTCOUNT('AM_AssetRegister'[UAID])
			VAR UAIDFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[UAID]) && SelectedUAIDsCount < AllUAIDsCount, 
			        "UAID = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[UAID]), 'AM_AssetRegister'[UAID], ", "), 
			        BLANK()
			    )
			
			-- ServiceType
			VAR AllServiceTypeCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ServiceType]), ALL('AM_AssetRegister'))
			VAR SelectedServiceTypeCount = DISTINCTCOUNT('AM_AssetRegister'[ServiceType])
			VAR ServiceTypeFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ServiceType]) && AllServiceTypeCount > SelectedServiceTypeCount, 
			        "Service Type = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ServiceType]), 'AM_AssetRegister'[ServiceType], ", "), 
			        BLANK()
			    )
			
			-- REGIONS
			VAR AllRegionsCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Region]), ALL('AM_AssetRegister'))
			VAR SelectedRegionsCount = DISTINCTCOUNT('AM_AssetRegister'[Region])
			VAR RegionFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Region]) && SelectedRegionsCount < AllRegionsCount, 
			        "Region = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Region]), 'AM_AssetRegister'[Region], ", "), 
			        BLANK()
			    )
			
			
			-- ServiceArea (Station)
			VAR AllServiceAreasCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ServiceArea]), ALL('AM_AssetRegister'))
			VAR SelectedServiceAreasCount = DISTINCTCOUNT('AM_AssetRegister'[ServiceArea])
			VAR ServiceAreaFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ServiceArea]) && AllServiceAreasCount > SelectedServiceAreasCount, 
			        "ServiceArea = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ServiceArea]), 'AM_AssetRegister'[ServiceArea], ", "), 
			        BLANK()
			    )
			
			-- Facility (Parent Facility)
			VAR AllFacilitysCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Facility]), ALL('AM_AssetRegister'))
			VAR SelectedFacilitysCount = DISTINCTCOUNT('AM_AssetRegister'[Facility])
			VAR FacilityFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Facility]) && AllFacilitysCount > SelectedFacilitysCount, 
			        "Facility = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Facility]), 'AM_AssetRegister'[Facility], ", "), 
			        BLANK()
			    )
			
			-- LocationName
			VAR AllLocationNamesCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[LocationName]), ALL('AM_AssetRegister'))
			VAR SelectedLocationNamesCount = DISTINCTCOUNT('AM_AssetRegister'[LocationName])
			VAR LocationNameFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[LocationName]) && AllLocationNamesCount > SelectedLocationNamesCount, 
			        "LocationName = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[LocationName]), 'AM_AssetRegister'[LocationName], ", "), 
			        BLANK()
			    )
			
			-- ProcessArea
			VAR AllProcessAreasCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ProcessArea]), ALL('AM_AssetRegister'))
			VAR SelectedProcessAreasCount = DISTINCTCOUNT('AM_AssetRegister'[ProcessArea])
			VAR ProcessAreaFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ProcessArea]) && AllProcessAreasCount > SelectedProcessAreasCount, 
			        "ProcessArea = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ProcessArea]), 'AM_AssetRegister'[ProcessArea], ", "), 
			        BLANK()
			    )
			-- SubProcessArea
			VAR AllSubProcessAreasCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[SubProcessArea]), ALL('AM_AssetRegister'))
			VAR SelectedSubProcessAreasCount = DISTINCTCOUNT('AM_AssetRegister'[SubProcessArea])
			VAR SubProcessAreaFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[SubProcessArea]) && AllSubProcessAreasCount > SelectedSubProcessAreasCount, 
			        "SubProcessArea = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[SubProcessArea]), 'AM_AssetRegister'[SubProcessArea], ", "), 
			        BLANK()
			    )
			    
			-- Assembly
			VAR AllAssemblyCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Assembly]), ALL('AM_AssetRegister'))
			VAR SelectedAssemblyCount = DISTINCTCOUNT('AM_AssetRegister'[Assembly])
			VAR AssemblyFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Assembly]) && AllAssemblyCount > SelectedAssemblyCount, 
			        "Assembly = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Assembly]), 'AM_AssetRegister'[Assembly], ", "), 
			        BLANK()
			    )
			
			-- Discipline
			VAR AllDisciplineCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Discipline]), ALL('AM_AssetRegister'))
			VAR SelectedDisciplineCount = DISTINCTCOUNT('AM_AssetRegister'[Discipline])
			VAR DisciplineFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Discipline]) && AllDisciplineCount > SelectedDisciplineCount, 
			        "Discipline = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Discipline]), 'AM_AssetRegister'[Discipline], ", "), 
			        BLANK()
			    )
			    
			-- AssetClass
			VAR AllAssetClassCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[AssetClass]), ALL('AM_AssetRegister'))
			VAR SelectedAssetClassCount = DISTINCTCOUNT('AM_AssetRegister'[AssetClass])
			VAR AssetClassFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[AssetClass]) && AllAssetClassCount > SelectedAssetClassCount, 
			        "AssetClass = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[AssetClass]), 'AM_AssetRegister'[AssetClass], ", "), 
			        BLANK()
			    )
			
			-- AssetType
			VAR AllAssetTypeCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[AssetType]), ALL('AM_AssetRegister'))
			VAR SelectedAssetTypeCount = DISTINCTCOUNT('AM_AssetRegister'[AssetType])
			VAR AssetTypeFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[AssetType]) && AllAssetClassCount > SelectedAssetClassCount, 
			        "AssetType = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[AssetType]), 'AM_AssetRegister'[AssetType], ", "), 
			        BLANK()
			    )
			
			-- AssetName
			VAR AllAssetNameCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[AssetName]), ALL('AM_AssetRegister'))
			VAR SelectedAssetNameCount = DISTINCTCOUNT('AM_AssetRegister'[AssetName])
			VAR AssetNameFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[AssetName]) && AllAssetNameCount > SelectedAssetNameCount, 
			        "AssetName = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[AssetName]), 'AM_AssetRegister'[AssetName], ", "), 
			        BLANK()
			    )
			
			-- CommissionDate
			VAR CommissionDateFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[CommissionDate]), 
			        "CommissionDate = " & 
			        FORMAT(MIN('AM_AssetRegister'[CommissionDate]), "MM/DD/YYYY") & 
			        " to " & 
			        FORMAT(MAX('AM_AssetRegister'[CommissionDate]), "MM/DD/YYYY"), 
			        BLANK()
			    )
			
			-- EUL
			VAR EULFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[EUL]), 
			        "EUL = " & 
			        MIN('AM_AssetRegister'[EUL]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[EUL]), 
			        BLANK()
			    )
			-- RUL_Calculated
			VAR RUL_CalculatedFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[RUL_Calculated]), 
			        "RUL_Calculated = " & 
			        MIN('AM_AssetRegister'[RUL_Calculated]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[RUL_Calculated]), 
			        BLANK()
			    )
			
			-- ReplacementYear
			VAR ReplacementYearFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ReplacementYear]), 
			        "ReplacementYear = " & 
			        MIN('AM_AssetRegister'[ReplacementYear]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[ReplacementYear]), 
			        BLANK()
			    )
			
			-- Condition
			VAR ConditionFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Condition]), 
			        "Condition = " & 
			        MIN('AM_AssetRegister'[Condition])& 
			        " to " & 
			        MAX('AM_AssetRegister'[Condition]), 
			        BLANK()
			    )
			------------------------Summary Page End-----------------------------
			
			-- Status
			VAR AllStatusCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Status]), ALL('AM_AssetRegister'))
			VAR SelectedStatusCount = DISTINCTCOUNT('AM_AssetRegister'[Status])
			VAR StatusFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Status]) && AllStatusCount > SelectedStatusCount, 
			        "Status = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Status]), 'AM_AssetRegister'[Status], ", "), 
			        BLANK()
			    )
			
			-- AssetLocation
			VAR AllAssetLocationCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[AssetLocation]), ALL('AM_AssetRegister'))
			VAR SelectedAssetLocationCount = DISTINCTCOUNT('AM_AssetRegister'[AssetLocation])
			VAR AssetLocationFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[AssetLocation]) && AllAssetLocationCount > SelectedAssetLocationCount, 
			        "AssetLocation = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[AssetLocation]), 'AM_AssetRegister'[AssetLocation], ", "), 
			        BLANK()
			    )
			
			-- Latitude
			VAR LatitudeFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Latitude]), 
			        "Latitude = " & 
			        MIN('AM_AssetRegister'[Latitude]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[Latitude]), 
			        BLANK()
			    )
			
			-- Logitude
			VAR LongitudeFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Longitude]), 
			        "Longitude = " & 
			        MIN('AM_AssetRegister'[Longitude]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[Longitude]), 
			        BLANK()
			    )
			
			-- UnitCostID
			VAR AllUnitCostIDCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[UnitCostID]), ALL('AM_AssetRegister'))
			VAR SelectedUnitCostIDCount = DISTINCTCOUNT('AM_AssetRegister'[UnitCostID])
			VAR UnitCostIDFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[UnitCostID]) && AllUnitCostIDCount > SelectedUnitCostIDCount, 
			        "UnitCostID = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[UNITCostID]), 'AM_AssetRegister'[UnitCostID], ", "), 
			        BLANK()
			    )
			
			-- UnitCostFixed
			VAR UnitCostFixedFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[UnitCost]), 
			        "UnitCost = " & 
			        MIN('AM_AssetRegister'[UnitCost]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[UnitCost]), 
			        BLANK()
			    )
			
			-- Unit
			VAR AllUnitCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Unit]), ALL('AM_AssetRegister'))
			VAR SelectedUnitCount = DISTINCTCOUNT('AM_AssetRegister'[Unit])
			VAR UnitFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Unit]) && AllUnitCount > SelectedUnitCount, 
			        "UnitCost = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Unit]), 'AM_AssetRegister'[Unit], ", "), 
			        BLANK()
			    )
			
			-- NumberOfUnits
			VAR NumberOfUnitsFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[NumberOfUnits]), 
			        "NumberOfUnits = " & 
			        MIN('AM_AssetRegister'[NumberOfUnits]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[NumberOfUnits]), 
			        BLANK()
			    )
			
			-- ReplacementCost_Static
			VAR ReplacementCost_StaticFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ReplacementCost_Static]), 
			        "ReplacementCost_Static = " & 
			        MIN('AM_AssetRegister'[ReplacementCost_Static]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[ReplacementCost_Static]), 
			        BLANK()
			    )
			
			-- ProjectTypeID
			VAR AllProjectTypeIDCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ProjectTypeID]), ALL('AM_AssetRegister'))
			VAR SelectedProjectTypeIDCount = DISTINCTCOUNT('AM_AssetRegister'[ProjectTypeID])
			VAR ProjectTypeIDFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ProjectTypeID]) && AllProjectTypeIDCount > SelectedProjectTypeIDCount, 
			        "ProjectTypeID = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ProjectTypeID]), 'AM_AssetRegister'[ProjectTypeID], ", "), 
			        BLANK()
			    )
			
			-------------------- ASSET Details End ---------------
			------------------ Condition Details Start -----------------
			
			-- ConditionAssessmentAssignedTo
			VAR AllConditionAssessmentAssignedToCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ConditionAssessmentAssignedTo]), ALL('AM_AssetRegister'))
			VAR SelectedConditionAssessmentAssignedToCount = DISTINCTCOUNT('AM_AssetRegister'[ConditionAssessmentAssignedTo])
			VAR ConditionAssessmentAssignedToFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ConditionAssessmentAssignedTo]) && AllConditionAssessmentAssignedToCount > SelectedConditionAssessmentAssignedToCount, 
			        "ConditionAssessmentAssignedTo = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ConditionAssessmentAssignedTo]), 'AM_AssetRegister'[ConditionAssessmentAssignedTo], ", "), 
			        BLANK()
			    )
			
			-- ConditionAssessmentPerformedBy
			VAR AllConditionAssessmentPerformedByCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ConditionAssessmentPerformedBy]), ALL('AM_AssetRegister'))
			VAR SelectedConditionAssessmentPerformedByCount = DISTINCTCOUNT('AM_AssetRegister'[ConditionAssessmentPerformedBy])
			VAR ConditionAssessmentPerformedByFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ConditionAssessmentPerformedBy]) && AllConditionAssessmentPerformedByCount > SelectedConditionAssessmentPerformedByCount, 
			        "ConditionAssessmentPerformedBy = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ConditionAssessmentPerformedBy]), 'AM_AssetRegister'[ConditionAssessmentPerformedBy], ", "), 
			        BLANK()
			    )
			
			-- ConditionAssessmentDate
			VAR ConditionAssessmentDateFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ConditionAssessmentDate]), 
			        "ConditionAssessmentDate = " & 
			        FORMAT(MIN('AM_AssetRegister'[ConditionAssessmentDate]), "MM/DD/YYYY") & 
			        " to " & 
			        FORMAT(MAX('AM_AssetRegister'[ConditionAssessmentDate]), "MM/DD/YYYY"), 
			        BLANK()
			    )
			
			-- ConditionAssessmentMethod
			VAR AllConditionAssessmentMethodCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ConditionAssessmentMethod]), ALL('AM_AssetRegister'))
			VAR SelectedConditionAssessmentMethodCount = DISTINCTCOUNT('AM_AssetRegister'[ConditionAssessmentMethod])
			VAR ConditionAssessmentMethodFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ConditionAssessmentMethod]) && AllConditionAssessmentMethodCount > SelectedConditionAssessmentMethodCount, 
			        "ConditionAssessmentMethod = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ConditionAssessmentMethod]), 'AM_AssetRegister'[ConditionAssessmentMethod], ", "), 
			        BLANK()
			    )
			
			-- CurrentYear
			VAR CurrentYearFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[CurrentYear]), 
			        "CurrentYear = " & 
			        MIN('AM_AssetRegister'[CurrentYear]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[CurrentYear]), 
			        BLANK()
			    )
			
			-- CurrentAge
			VAR CurrentAgeFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[CurrentAge]), 
			        "CurrentAge = " & 
			        MIN('AM_AssetRegister'[CurrentAge]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[CurrentAge]), 
			        BLANK()
			    )
			
			-- PercentUsed_Implied
			VAR PercentUsed_ImpliedFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[PercentUsed_Implied]), 
			        "PercentUsed_Implied = " & 
			        MIN('AM_AssetRegister'[PercentUsed_Implied]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[PercentUsed_Implied]), 
			        BLANK()
			    )
			
			-- PercentUsed_High
			VAR PercentUsed_HighFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[PercentUsed_High]), 
			        "PercentUsed_High = " & 
			        MIN('AM_AssetRegister'[PercentUsed_High]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[PercentUsed_High]), 
			        BLANK()
			    )
			
			-- PercentUsed_Low
			VAR PercentUsed_LowFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[PercentUsed_Low]), 
			        "PercentUsed_Low = " & 
			        MIN('AM_AssetRegister'[PercentUsed_Low]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[PercentUsed_Low]), 
			        BLANK()
			    )
			
			-- PercentUsed_Calculated
			VAR PercentUsed_CalculatedFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[PercentUsed_Calculated]), 
			        "PercentUsed_Calculated = " & 
			        MIN('AM_AssetRegister'[PercentUsed_Calculated]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[PercentUsed_Calculated]), 
			        BLANK()
			    )
			
			-- ReplacementYear_Age
			VAR ReplacementYear_AgeFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ReplacementYear_Age]), 
			        "ReplacementYear_Age = " & 
			        MIN('AM_AssetRegister'[ReplacementYear_Age]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[ReplacementYear_Age]), 
			        BLANK()
			    )
			
			-- ReplacementYear_Condition
			VAR ReplacementYear_ConditionFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ReplacementYear_Condition]), 
			        "ReplacementYear_Condition = " & 
			        MIN('AM_AssetRegister'[ReplacementYear_Condition]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[ReplacementYear_Condition]), 
			        BLANK()
			    )
			
			-- RUL_Age
			VAR RUL_AgeFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[RUL_Age]), 
			        "RUL_Age = " & 
			        MIN('AM_AssetRegister'[RUL_Age]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[RUL_Age]), 
			        BLANK()
			    )
			
			-- RUL_Implied
			VAR RUL_ImpliedFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[RUL_Implied]), 
			        "RUL_Implied = " & 
			        MIN('AM_AssetRegister'[RUL_Implied]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[RUL_Implied]), 
			        BLANK()
			    )
			
			-- RUL_Implied
			VAR RUL_ImpliedsFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[RUL_Implied]), 
			        "RUL_Implied = " & 
			        MIN('AM_AssetRegister'[RUL_Implied]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[RUL_Implied]), 
			        BLANK()
			    )
			
			-- RUL_Condition
			VAR RUL_ConditionFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[RUL_Condition]), 
			        "RUL_Condition = " & 
			        MIN('AM_AssetRegister'[RUL_Condition]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[RUL_Condition]), 
			        BLANK()
			    )
			
			-- FailureModeFilter
			VAR AllFailureModeCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[FailureMode]), ALL('AM_AssetRegister'))
			VAR SelectedFailureModeCount = DISTINCTCOUNT('AM_AssetRegister'[FailureMode])
			VAR FailureModeFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[FailureMode]) && AllFailureModeCount > SelectedFailureModeCount, 
			        "FailureMode = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[FailureMode]), 'AM_AssetRegister'[FailureMode], ", "), 
			        BLANK()
			    )
			
			-- POF_Age
			VAR POF_AgeFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[POF_Age]), 
			        "POF_Age = " & 
			        MIN('AM_AssetRegister'[POF_Age]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[POF_Age]), 
			        BLANK()
			    )
			
			-- RehabDate
			VAR RehabDateFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[RehabDate]), 
			        "RehabDate = " & 
			        FORMAT(MIN('AM_AssetRegister'[RehabDate]), "MM/DD/YYYY") & 
			        " to " & 
			        FORMAT(MAX('AM_AssetRegister'[RehabDate]), "MM/DD/YYYY"), 
			        BLANK()
			    )
			
			-- POF_Static
			VAR POF_StaticFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[POF_Static]), 
			        "POF_Static = " & 
			        MIN('AM_AssetRegister'[POF_Static]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[POF_Static]), 
			        BLANK()
			    )
			
			-- COF_Static
			VAR COF_StaticFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[COF_Static]), 
			        "COF_Static = " & 
			        MIN('AM_AssetRegister'[COF_Static]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[COF_Static]), 
			        BLANK()
			    )
			
			-- Risk_Static
			VAR Risk_StaticFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Risk_Static]), 
			        "Risk_Static = " & 
			        MIN('AM_AssetRegister'[Risk_Static]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[Risk_Static]), 
			        BLANK()
			    )
			
			------------------ Condition Details End -----------------
			------------------ PHysical Details Start ----------------
			-- PhysicalDataDate
			VAR PhysicalDataDateFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[PhysicalDataDate]), 
			        "PhysicalDataDate = " & 
			        FORMAT(MIN('AM_AssetRegister'[PhysicalDataDate]), "MM/DD/YYYY") & 
			        " to " & 
			        FORMAT(MAX('AM_AssetRegister'[PhysicalDataDate]), "MM/DD/YYYY"), 
			        BLANK()
			    )
			
			-- Size1
			VAR AllSize1Count = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Size1]), ALL('AM_AssetRegister'))
			VAR SelectedSize1Count = DISTINCTCOUNT('AM_AssetRegister'[Size1])
			VAR Size1Filter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Size1]) && AllSize1Count > SelectedSize1Count, 
			        "Size1 = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Size1]), 'AM_AssetRegister'[Size1], ", "), 
			        BLANK()
			    )
			
			-- Size2
			VAR AllSize2Count = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Size2]), ALL('AM_AssetRegister'))
			VAR SelectedSize2Count = DISTINCTCOUNT('AM_AssetRegister'[Size2])
			VAR Size2Filter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Size2]) && AllSize1Count > SelectedSize2Count, 
			        "Size2 = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Size2]), 'AM_AssetRegister'[Size2], ", "), 
			        BLANK()
			    )
			
			-- Size3
			VAR AllSize3Count = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Size3]), ALL('AM_AssetRegister'))
			VAR SelectedSize3Count = DISTINCTCOUNT('AM_AssetRegister'[Size3])
			VAR Size3Filter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Size3]) && AllSize3Count > SelectedSize3Count, 
			        "Size3 = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Size3]), 'AM_AssetRegister'[Size3], ", "), 
			        BLANK()
			    )
			
			-- Area
			VAR AllAreaCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Area]), ALL('AM_AssetRegister'))
			VAR SelectedAreaCount = DISTINCTCOUNT('AM_AssetRegister'[Area])
			VAR AreaFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Area]) && AllAreaCount > SelectedAreaCount, 
			        "Area = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Area]), 'AM_AssetRegister'[Area], ", "), 
			        BLANK()
			    )
			
			-- ClearSpan
			VAR AllClearSpanCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ClearSpan]), ALL('AM_AssetRegister'))
			VAR SelectedClearSpanCount = DISTINCTCOUNT('AM_AssetRegister'[ClearSpan])
			VAR ClearSpanFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ClearSpan]) && AllClearSpanCount > SelectedClearSpanCount, 
			        "ClearSpan = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ClearSpan]), 'AM_AssetRegister'[ClearSpan], ", "), 
			        BLANK()
			    )
			
			-- ConfinedSpace
			VAR AllConfinedSpaceCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ConfinedSpace]), ALL('AM_AssetRegister'))
			VAR SelectedConfinedSpaceCount = DISTINCTCOUNT('AM_AssetRegister'[ConfinedSpace])
			VAR ConfinedSpaceFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ConfinedSpace]) && AllConfinedSpaceCount > SelectedConfinedSpaceCount, 
			        "ConfinedSpace = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ConfinedSpace]), 'AM_AssetRegister'[ConfinedSpace], ", "), 
			        BLANK()
			    )
			
			-- Diameter
			VAR AllDiameterCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Diameter]), ALL('AM_AssetRegister'))
			VAR SelectedDiameterCount = DISTINCTCOUNT('AM_AssetRegister'[Diameter])
			VAR DiameterFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Diameter]) && AllDiameterCount > SelectedDiameterCount, 
			        "Diameter = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Diameter]), 'AM_AssetRegister'[Diameter], ", "), 
			        BLANK()
			    )
			
			-- DutyFlow
			VAR AllDutyFlowCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[DutyFlow]), ALL('AM_AssetRegister'))
			VAR SelectedDutyFlowCount = DISTINCTCOUNT('AM_AssetRegister'[DutyFlow])
			VAR DutyFlowFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[DutyFlow]) && AllDutyFlowCount > SelectedDutyFlowCount, 
			        "DutyFlow = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[DutyFlow]), 'AM_AssetRegister'[DutyFlow], ", "), 
			        BLANK()
			    )
			
			-- DutyHead
			VAR AllDutyHeadCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[DutyHead]), ALL('AM_AssetRegister'))
			VAR SelectedDutyHeadCount = DISTINCTCOUNT('AM_AssetRegister'[DutyHead])
			VAR DutyHeadFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[DutyHead]) && AllDutyHeadCount > SelectedDutyHeadCount, 
			        "DutyHead = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[DutyHead]), 'AM_AssetRegister'[DutyHead], ", "), 
			        BLANK()
			    )
			
			-- Elevation
			VAR ElevationFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Elevation]), 
			        "Elevation = " & 
			        MIN('AM_AssetRegister'[Elevation]) & 
			        " to " & 
			        MAX('AM_AssetRegister'[Elevation]), 
			        BLANK()
			    )
			
			-- HeightDepthFilter
			VAR AllHeightDepthCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[HeightDepth]), ALL('AM_AssetRegister'))
			VAR SelectedHeightDepthCount = DISTINCTCOUNT('AM_AssetRegister'[HeightDepth])
			VAR HeightDepthFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[HeightDepth]) && AllHeightDepthCount > SelectedHeightDepthCount, 
			        "HeightDepth = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[HeightDepth]), 'AM_AssetRegister'[HeightDepth], ", "), 
			        BLANK()
			    )
			
			-- LayerName
			VAR AllLayerNameCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[LayerName]), ALL('AM_AssetRegister'))
			VAR SelectedLayerNameCount = DISTINCTCOUNT('AM_AssetRegister'[LayerName])
			VAR LayerNameFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[LayerName]) && AllLayerNameCount > SelectedLayerNameCount, 
			        "LayerName = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[LayerName]), 'AM_AssetRegister'[LayerName], ", "), 
			        BLANK()
			    )
			
			-- Length
			VAR AllLengthCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Length]), ALL('AM_AssetRegister'))
			VAR SelectedLengthCount = DISTINCTCOUNT('AM_AssetRegister'[Length])
			VAR LengthFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Length]) && AllLengthCount > SelectedLengthCount, 
			        "Length = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Length]), 'AM_AssetRegister'[Length], ", "), 
			        BLANK()
			    )
			
			-- Manufacturer
			VAR AllManufacturerCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Manufacturer]), ALL('AM_AssetRegister'))
			VAR SelectedManufacturerCount = DISTINCTCOUNT('AM_AssetRegister'[Manufacturer])
			VAR ManufacturerFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Manufacturer]) && AllManufacturerCount > SelectedManufacturerCount, 
			        "Manufacturer = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Manufacturer]), 'AM_AssetRegister'[Manufacturer], ", "), 
			        BLANK()
			    )
			
			-- Material
			VAR AllMaterialCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Material]), ALL('AM_AssetRegister'))
			VAR SelectedMaterialCount = DISTINCTCOUNT('AM_AssetRegister'[Material])
			VAR MaterialFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Material]) && AllMaterialCount > SelectedMaterialCount, 
			        "Material = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Material]), 'AM_AssetRegister'[Material], ", "), 
			        BLANK()
			    )
			
			-- Model
			VAR AllModelCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Model]), ALL('AM_AssetRegister'))
			VAR SelectedModelCount = DISTINCTCOUNT('AM_AssetRegister'[Model])
			VAR ModelFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Model]) && AllModelCount > SelectedModelCount, 
			        "Model = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Model]), 'AM_AssetRegister'[Model], ", "), 
			        BLANK()
			    )
			
			-- Power
			VAR AllPowerCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Power]), ALL('AM_AssetRegister'))
			VAR SelectedPowerCount = DISTINCTCOUNT('AM_AssetRegister'[Power])
			VAR PowerFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Power]) && AllPowerCount > SelectedPowerCount, 
			        "Power = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Power]), 'AM_AssetRegister'[Power], ", "), 
			        BLANK()
			    )
			
			-- SerialNumber
			VAR AllSerialNumberCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[SerialNumber]), ALL('AM_AssetRegister'))
			VAR SelectedSerialNumberCount = DISTINCTCOUNT('AM_AssetRegister'[SerialNumber])
			VAR SerialNumberFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[SerialNumber]) && AllSerialNumberCount > SelectedSerialNumberCount, 
			        "SerialNumber = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[SerialNumber]), 'AM_AssetRegister'[SerialNumber], ", "), 
			        BLANK()
			    )  
			
			-- SignalInOut
			VAR AllSignalInOutCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[SignalInOut]), ALL('AM_AssetRegister'))
			VAR SelectedSignalInOutCount = DISTINCTCOUNT('AM_AssetRegister'[SignalInOut])
			VAR SerialSignalInOutFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[SignalInOut]) && AllSignalInOutCount > SelectedSignalInOutCount, 
			        "SignalInOut = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[SignalInOut]), 'AM_AssetRegister'[SignalInOut], ", "), 
			        BLANK()
			    )    
			
			-- Volume
			VAR AllVolumeCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Volume]), ALL('AM_AssetRegister'))
			VAR SelectedVolumeCount = DISTINCTCOUNT('AM_AssetRegister'[Volume])
			VAR VolumeFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Volume]) && AllVolumeCount > SelectedVolumeCount, 
			        "Volume = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Volume]), 'AM_AssetRegister'[Volume], ", "), 
			        BLANK()
			    )    
			
			-- Width
			VAR AllWidthCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Width]), ALL('AM_AssetRegister'))
			VAR SelectedWidthCount = DISTINCTCOUNT('AM_AssetRegister'[Width])
			VAR WidthFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Width]) && AllWidthCount > SelectedWidthCount, 
			        "Width = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Width]), 'AM_AssetRegister'[Width], ", "), 
			        BLANK()
			    )    
			
			
			------------------ PHysical Details End ----------------
			----------------- Resources Start ------------
			-- ID_CMMS
			VAR AllID_CMMSCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ID_CMMS]), ALL('AM_AssetRegister'))
			VAR SelectedID_CMMSCount = DISTINCTCOUNT('AM_AssetRegister'[ID_CMMS])
			VAR ID_CMMSFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ID_CMMS]) && AllID_CMMSCount > SelectedID_CMMSCount, 
			        "ID_CMMS = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ID_CMMS]), 'AM_AssetRegister'[ID_CMMS], ", "), 
			        BLANK()
			    )
			
			-- ID_PID
			VAR AllID_PIDCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ID_PID]), ALL('AM_AssetRegister'))
			VAR SelectedID_PIDCount = DISTINCTCOUNT('AM_AssetRegister'[ID_PID])
			VAR ID_PIDFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ID_PID]) && AllID_PIDCount > SelectedID_PIDCount, 
			        "ID_PID = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ID_PID]), 'AM_AssetRegister'[ID_PID], ", "), 
			        BLANK()
			    )
			
			-- ObjectID
			VAR AllObjectIDCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ObjectID]), ALL('AM_AssetRegister'))
			VAR SelectedObjectIDCount = DISTINCTCOUNT('AM_AssetRegister'[ObjectID])
			VAR ObjectIDFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ObjectID]) && AllObjectIDCount > SelectedObjectIDCount, 
			        "ObjectID = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ObjectID]), 'AM_AssetRegister'[ObjectID], ", "), 
			        BLANK()
			    )
			
			-- ID_Document
			VAR AllID_DocumentCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ID_Document]), ALL('AM_AssetRegister'))
			VAR SelectedID_DocumentCount = DISTINCTCOUNT('AM_AssetRegister'[ID_Document])
			VAR ID_DocumentFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ID_Document]) && AllID_DocumentCount > SelectedID_DocumentCount, 
			        "ID_Document = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ID_Document]), 'AM_AssetRegister'[ID_Document], ", "), 
			        BLANK()
			    )
			
			-- ID_Financial
			VAR AllID_FinancialCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[ID_Financial]), ALL('AM_AssetRegister'))
			VAR SelectedID_FinancialCount = DISTINCTCOUNT('AM_AssetRegister'[ID_Financial])
			VAR ID_FinancialFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[ID_Financial]) && AllID_FinancialCount > SelectedID_FinancialCount, 
			        "ID_Document = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[ID_Financial]), 'AM_AssetRegister'[ID_Financial], ", "), 
			        BLANK()
			    )
			
			-- URL_Manual
			VAR AllURL_ManualCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[URL_Manual]), ALL('AM_AssetRegister'))
			VAR SelectedURL_ManualCount = DISTINCTCOUNT('AM_AssetRegister'[URL_Manual])
			VAR URL_ManualFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[URL_Manual]) && AllURL_ManualCount > SelectedURL_ManualCount, 
			        "URL_Manual = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[URL_Manual]), 'AM_AssetRegister'[URL_Manual], ", "), 
			        BLANK()
			    )
			
			-- URL_Report
			VAR AllURL_ReportCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[URL_Report]), ALL('AM_AssetRegister'))
			VAR SelectedURL_ReportCount = DISTINCTCOUNT('AM_AssetRegister'[URL_Report])
			VAR URL_ReportFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[URL_Report]) && AllURL_ReportCount > SelectedURL_ReportCount, 
			        "URL_Report = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[URL_Report]), 'AM_AssetRegister'[URL_Report], ", "), 
			        BLANK()
			    )
			
			-- Comments_AMFilter
			VAR AllComments_AMCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Comments_AM]), ALL('AM_AssetRegister'))
			VAR SelectedComments_AMCount = DISTINCTCOUNT('AM_AssetRegister'[Comments_AM])
			VAR Comments_AMFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Comments_AM]) && SelectedComments_AMCount < AllComments_AMCount, 
			        "Comments_AM = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Comments_AM]), 'AM_AssetRegister'[Comments_AM], ", "), 
			        BLANK()
			    )
			
			-- Comments_Financial
			VAR AllComments_FinancialCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Comments_Financial]), ALL('AM_AssetRegister'))
			VAR SelectedComments_FinancialCount = DISTINCTCOUNT('AM_AssetRegister'[Comments_Financial])
			VAR Comments_FinancialFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Comments_Financial]) && SelectedComments_FinancialCount < AllComments_FinancialCount, 
			        "Comments_Financial = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Comments_Financial]), 'AM_AssetRegister'[Comments_Financial], ", "), 
			        BLANK()
			    )
			
			-- Comments_GIS
			VAR AllComments_GISCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Comments_GIS]), ALL('AM_AssetRegister'))
			VAR SelectedComments_GISCount = DISTINCTCOUNT('AM_AssetRegister'[Comments_GIS])
			VAR Comments_GISFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Comments_GIS]) && SelectedComments_GISCount < AllComments_GISCount, 
			        "Comments_GIS = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Comments_GIS]), 'AM_AssetRegister'[Comments_GIS], ", "), 
			        BLANK()
			    )
			
			-- Comments_Hierarchy
			VAR AllComments_HierarchyCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Comments_Hierarchy]), ALL('AM_AssetRegister'))
			VAR SelectedComments_HierarchyCount = DISTINCTCOUNT('AM_AssetRegister'[Comments_Hierarchy])
			VAR Comments_HierarchyFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Comments_Hierarchy]) && SelectedComments_HierarchyCount < AllComments_HierarchyCount, 
			        "Comments_Hierarchy = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Comments_Hierarchy]), 'AM_AssetRegister'[Comments_Hierarchy], ", "), 
			        BLANK()
			    )
			
			-- Comments_Operator
			VAR AllComments_OperatorCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Comments_Operator]), ALL('AM_AssetRegister'))
			VAR SelectedComments_OperatorCount = DISTINCTCOUNT('AM_AssetRegister'[Comments_Operator])
			VAR Comments_OperatorFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Comments_Operator]) && SelectedComments_OperatorCount < AllComments_OperatorCount, 
			        "Comments_Operator = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Comments_Operator]), 'AM_AssetRegister'[Comments_Operator], ", "), 
			        BLANK()
			    )
			
			-- Comments_PhysicalFunctional
			VAR AllComments_PhysicalFunctionalCount = CALCULATE(DISTINCTCOUNT('AM_AssetRegister'[Comments_PhysicalFunctional]), ALL('AM_AssetRegister'))
			VAR SelectedComments_PhysicalFunctionalCount = DISTINCTCOUNT('AM_AssetRegister'[Comments_PhysicalFunctional])
			VAR Comments_PhysicalFunctionalFilter =
			    IF(
			        ISFILTERED('AM_AssetRegister'[Comments_PhysicalFunctional]) && SelectedComments_PhysicalFunctionalCount < AllComments_PhysicalFunctionalCount, 
			        "Comments_PhysicalFunctional = " & CONCATENATEX(DISTINCT('AM_AssetRegister'[Comments_PhysicalFunctional]), 'AM_AssetRegister'[Comments_PhysicalFunctional], ", "), 
			        BLANK()
			    )
			
			----------------- Resources End -----------------
			VAR CombinedFilters = 
			    CONCATENATEX(
			        FILTER(
			            {
			                UAIDFilter, ServiceTypeFilter, RegionFilter, ServiceAreaFilter, FacilityFilter, LocationNameFilter, ProcessAreaFilter, SubProcessAreaFilter, AssemblyFilter, DisciplineFilter, AssetClassFilter, AssetTypeFilter, AssetNameFilter, CommissionDateFilter, ConditionFilter, EULFilter, RUL_CalculatedFilter, ReplacementYearFilter, StatusFilter, AssetLocationFilter, LatitudeFilter, LongitudeFilter, UnitCostIDFilter, UnitCostFixedFilter, UnitFilter, NumberOfUnitsFilter, ReplacementCost_StaticFilter, ProjectTypeIDFilter, ConditionAssessmentAssignedToFilter, ConditionAssessmentPerformedByFilter, ConditionAssessmentDateFilter, ConditionAssessmentMethodFilter, CurrentYearFilter, CurrentAgeFilter, PercentUsed_ImpliedFilter, PercentUsed_HighFilter, PercentUsed_LowFilter, PercentUsed_CalculatedFilter, ReplacementYear_AgeFilter, ReplacementYear_ConditionFilter, RUL_AgeFilter, RUL_ImpliedsFilter, RUL_ConditionFilter, FailureModeFilter, POF_AgeFilter, RehabDateFilter, POF_StaticFilter, COF_StaticFilter, Risk_StaticFilter, PhysicalDataDateFilter,Size1Filter, Size2Filter, Size3Filter, AreaFilter, ClearSpanFilter, ConfinedSpaceFilter, DiameterFilter,DutyFlowFilter, HeightDepthFilter, DutyHeadFilter, LengthFilter, LayerNameFilter, MaterialFilter, ManufacturerFilter, ModelFilter, PowerFilter, SerialNumberFilter, SerialSignalInOutFilter, VolumeFilter, WidthFilter, ID_CMMSFilter, ID_PIDFilter, ObjectIDFilter, ID_DocumentFilter, ID_FinancialFilter, URL_ReportFilter, URL_ManualFilter, Comments_AMFilter, Comments_FinancialFilter, Comments_GISFilter, Comments_HierarchyFilter, Comments_OperatorFilter, Comments_PhysicalFunctionalFilter
			            },
			            NOT(ISBLANK([Value]))  
			        ),
			        [Value], 
			        ", "
			    )
			
			RETURN 
			IF(ISBLANK(CombinedFilters), "No Filters Applied", CONCATENATE("Filters Applied: ", CombinedFilters))
			
			```
		lineageTag: 7b889736-22b0-4313-8727-c693d28d57cd

	measure GroupVisibility = ```
			
			SWITCH(
			    SELECTEDVALUE('AM_AssetRegister_Fields_Groups'[Ordinal]),
			    1, "Summary", 
			    2, "Asset Details", 
			    3, "Condition Details", 
			    4, "Physical Details",
			    5, "Resources", 
			    6, "Other", 
			    BLANK()
			)
			
			```
		lineageTag: 7ed125b8-84eb-4de8-8655-965da1661481

	measure Show_AssetDetails = ```
			
			IF([GroupVisibility] = "Asset Details", 1, 0)
			
			
			```
		formatString: 0
		lineageTag: d6a4c4e1-943f-44dc-957c-42b778f6b19c

	measure Show_ConditionDetails = ```
			
			IF([GroupVisibility] = "Condition Details", 1, 0)
			
			```
		formatString: 0
		lineageTag: d4093511-6ec1-4fbd-bc3b-bddd0c5a782a

	measure Show_Other =
			
			IF([GroupVisibility] = "Other", 1, 0)
		formatString: 0
		lineageTag: f1cb1d3f-fcee-41f4-8386-302925514539

	measure Show_PhysicalDetails = ```
			
			IF([GroupVisibility] = "Physical Details", 1, 0)
			
			
			```
		formatString: 0
		lineageTag: 268908be-a969-47d8-85f9-526e696b674a

	measure Show_Resources = ```
			
			IF([GroupVisibility] = "Resources", 1, 0)
			
			
			```
		formatString: 0
		lineageTag: a5f8f161-c6bc-4895-ae7e-537cf1f2e6af

	measure Show_Summary = ```
			
			IF([GroupVisibility] = "Summary", 1, 0)
			
			```
		formatString: 0
		lineageTag: 344fc129-53ee-48f2-98f8-3c557e76533e

	measure m_SelectedFieldName =
			
			SELECTEDVALUE('AM_AssetRegister_Fields'[FieldName])
		lineageTag: 7b081235-ee37-452d-95a4-62256e817702

	measure m_SelectedUAIDs =
			
			VAR T = VALUES('AM_AssetRegister'[UAID])
			RETURN
			    CONCATENATEX(T, "'" & 'AM_AssetRegister'[UAID] & "'", ",")
		lineageTag: 269e7538-2751-4a70-99d1-b03c5e0cb4f7

	measure SelectedFieldName_Display =
			
			SELECTEDVALUE('AM_AssetRegister_Fields'[FieldName], "(Select Field)")
		lineageTag: 2be8d548-3ee1-4b39-a983-e8256fb4edf7

	measure UAIDs_Concat_Quoted =
			
			VAR UaidTable =
			    FILTER (
			        DISTINCT ( 'AM_AssetRegister'[UAID] ),
			        NOT ISBLANK ( 'AM_AssetRegister'[UAID] )
			    )
			RETURN
			    CONCATENATEX (
			        UaidTable,
			        "'" & 'AM_AssetRegister'[UAID] & "'",  -- wrap each UAID in quotes
			        ",",                                     -- delimiter: "','
			        'AM_AssetRegister'[UAID],
			        ASC
			    )
		lineageTag: c0fc8a20-f138-413b-8f21-5298c2a50f7c

	column Column
		formatString: 0
		lineageTag: 0a22c65a-6dae-4729-94a8-aee5a6f4a051
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _Measures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 0c9d51e43df34288b3911749ab6d97dd

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

